In [1]:
import numpy as np

creating 1d arry

In [7]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_3d)
arr_4d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr_4d)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
