In [1]:
import numpy as np

creating 1d arry

In [2]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_3d)
arr_4d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr_4d)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
#checking number of demention
print(arr_2d.ndim)
#checking shape of array
print(arr_3d.shape)
#checking total number of elements 
print(arr_4d.size)

2
(3, 3)
12


In [8]:
sample_arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(sample_arr[::-1])

[10  9  8  7  6  5  4  3  2  1  0]


In [13]:
sample_arr2d = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
# print(sample_arr2d[:2, :3])
print(sample_arr2d[::-1])

[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [15]:
arr1 = np.array([1,2,3,])
arr2 = np.array([4,5,6,])

print(arr1 + arr2)
print('-' * 40 )
print(arr1 - arr2)
print('-' * 40 )
print(arr1 * arr2)
print('-' * 40 )
print(arr1 / arr2)
print('-' * 40 )
print(arr1 ** arr2)
print('-' * 40 )
print(arr1 % arr2)
print('-' * 40 )
print(arr1 // arr2)


[5 7 9]
----------------------------------------
[-3 -3 -3]
----------------------------------------
[ 4 10 18]
----------------------------------------
[0.25 0.4  0.5 ]
----------------------------------------
[  1  32 729]
----------------------------------------
[1 2 3]
----------------------------------------
[0 0 0]
